import '../models/spot.dart';

/// 内置景点数据（大理洱海）
final List<Spot> kDefaultSpots = [
  Spot(
    id: 'xizhou',
    name: '喜洲古镇',
    emoji: '🏘️',
    lat: 25.9014,
    lng: 100.1197,
    meta: '往返 4.8km · 14分钟',
    desc: '白族民居建筑群，推荐品尝喜洲粑粑。',
    color: '#FFB6C1',
    category: '打卡',
  ),
  Spot(
    id: 'shuanglang',
    name: '双廊古镇',
    emoji: '🌅',
    lat: 25.9611,
    lng: 100.2211,
    meta: '往返 16km · 1小时',
    desc: '苍洱风光第一村，夕阳景色绝美。',
    color: '#87CEEB',
    category: '打卡',
  ),
  Spot(
    id: 'xiaoputo',
    name: '小普陀',
    emoji: '🦅',
    lat: 25.8667,
    lng: 100.2050,
    meta: '往返 15km · 25分钟',
    desc: '冬季红嘴鸥聚集地，洱海中的袖珍岛屿。',
    color: '#87CEEB',
    category: '打卡',
  ),
  Spot(
    id: 'cuncun',
    name: '才村码头',
    emoji: '🚴',
    lat: 25.7480,
    lng: 100.1620,
    meta: '10km · 20分钟',
    desc: '环海骑行起点，离古城最近的海边。',
    color: '#FFB6C1',
    category: '打卡',
  ),
  Spot(
    id: 'longkan',
    name: '龙龛码头',
    emoji: '🌄',
    lat: 25.6720,
    lng: 100.1480,
    meta: '日出胜地 · 水杉林',
    desc: '观赏洱海日出的顶级机位，水杉林倒影极美。',
    color: '#FFB6C1',
    category: '打卡',
  ),
  Spot(
    id: 'dali',
    name: '大理古城',
    emoji: '🏯',
    lat: 25.6942,
    lng: 100.1608,
    meta: '旅途起点 · 文献名邦',
    desc: '五华楼 × 人民路，底蕴深厚。',
    color: '#DDA0DD',
    category: '打卡',
  ),
  Spot(
    id: 'binhe',
    name: '挖色镇',
    emoji: '🌊',
    lat: 25.8050,
    lng: 100.2480,
    meta: '5km · 6分钟',
    desc: '静谧海滨小镇，游客少，适合慢游。',
    color: '#87CEEB',
    category: '打卡',
  ),
  Spot(
    id: 'wenshucun',
    name: '文笔村',
    emoji: '🎨',
    lat: 25.7380,
    lng: 100.2350,
    meta: '4.5km · 8分钟',
    desc: '充满文艺氛围的小村落，民宿和小店众多。',
    color: '#87CEEB',
    category: '打卡',
  ),
];
